var drivers = [
  {
    name: "Lewis",
    surname: "Hamilton",
    team: "Mercedes",
    powerPoints: 9,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "George",
    surname: "Russell",
    team: "Mercedes",
    powerPoints: 7,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Max",
    surname: "Verstappen",
    team: "Red Bull",
    powerPoints: 9,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Sergio",
    surname: "Perez",
    team: "Red Bull",
    powerPoints: 7,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Lando",
    surname: "Norris",
    team: "Mclaren",
    powerPoints: 6,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Daniel",
    surname: "Ricciardo",
    team: "Mclaren",
    powerPoints: 5,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Alex",
    surname: "Albon",
    team: "Williams",
    powerPoints: 5,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Nicholas",
    surname: "Latifi",
    team: "Williams",
    powerPoints: 3,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Charles",
    surname: "Leclerc",
    team: "Ferrari",
    powerPoints: 8,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Carlos",
    surname: "Sainz",
    team: "Ferrari",
    powerPoints: 7,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Kevin",
    surname: "Magnussen",
    team: "Haas",
    powerPoints: 4,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Mick",
    surname: "Schumacher",
    team: "Haas",
    powerPoints: 4,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Sebastian",
    surname: "Vettel",
    team: "Aston Martin",
    powerPoints: 4,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Lance",
    surname: "Stroll",
    team: "Aston Martin",
    powerPoints: 5,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Fernando",
    surname: "Alonso",
    team: "Alpine",
    powerPoints: 6,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Esteban",
    surname: "Ocon",
    team: "Alpine",
    powerPoints: 6,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Pierre",
    surname: "Gasly",
    team: "AlphaTauri",
    powerPoints: 6,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Yuki",
    surname: "Tsunoda",
    team: "AlphaTauri",
    powerPoints: 5,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Valettri",
    surname: "Bottas",
    team: "Alfa Romeo",
    powerPoints: 6,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
  {
    name: "Guanyu",
    surname: "Zhou",
    team: "Alfa Romeo",
    powerPoints: 5,
    qualiPoints: 0,
    gridPosition: 0,
    qualiGrid: 0,
    racingPoints: 0,
  },
];
